// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruitmentBackend.Data;

#nullable disable

namespace OnBoarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310070254_InitialDatabaseSetup")]
    partial class InitialDatabaseSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentBackend.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode", "CompanyId");

                    b.HasIndex("CandidateId", "PositionCode", "CompanyId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.BranchCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("brhloccode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brhlocname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("branch_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryOfOriginCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disability")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatusCode")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("NationalityCode")
                        .HasColumnType("text");

                    b.Property<string>("NativeStatus")
                        .HasColumnType("text");

                    b.Property<string>("NewIcNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldIcNumber")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("RaceCode")
                        .HasColumnType("text");

                    b.Property<string>("RecommendationDetails")
                        .HasColumnType("text");

                    b.Property<string>("RecommendationType")
                        .HasColumnType("text");

                    b.Property<string>("Referee1")
                        .HasColumnType("text");

                    b.Property<string>("Referee2")
                        .HasColumnType("text");

                    b.Property<string>("ReligionCode")
                        .HasColumnType("text");

                    b.Property<string>("SalutationCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("CountryOfOriginCode");

                    b.HasIndex("MaritalStatusCode");

                    b.HasIndex("NationalityCode");

                    b.HasIndex("RaceCode");

                    b.HasIndex("ReligionCode");

                    b.HasIndex("SalutationCode");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityLevel")
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HobbyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateHobbies");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadLevel")
                        .HasColumnType("text");

                    b.Property<string>("SpokenLevel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WrittenLevel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateLanguages");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateResume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateResumes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CessationReason", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("rsgnrsncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rsgnrsndesc");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("cessation_reasons");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColourCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("colour_code");

                    b.Property<string>("CompanyDetails")
                        .HasColumnType("text")
                        .HasColumnName("company_details");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CompanyCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("compnycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compnyname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("company_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ContactInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrespondenceAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correspondence_address");

                    b.Property<string>("CorrespondencePhone")
                        .HasColumnType("text")
                        .HasColumnName("correspondence_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyAddress")
                        .HasColumnType("text")
                        .HasColumnName("emergency_address");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("text")
                        .HasColumnName("emergency_phone");

                    b.Property<string>("OfficeNumber")
                        .HasColumnType("text")
                        .HasColumnName("office_number");

                    b.Property<string>("OtherNumber")
                        .HasColumnType("text")
                        .HasColumnName("other_number");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("text")
                        .HasColumnName("permanent_address");

                    b.Property<string>("PermanentPhone")
                        .HasColumnType("text")
                        .HasColumnName("permanent_phone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("ContactInformation");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CountryOrigin", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("ctyorgcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ctyorgname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("country_origin_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.DepartmentCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("departcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("department_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.DivisionCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("divisncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisnname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("division_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CessationReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("CessationReasonDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmphJobName")
                        .HasColumnType("text");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndustryCode")
                        .HasColumnType("text");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobFunction")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<decimal?>("LastSalary")
                        .HasColumnType("numeric");

                    b.Property<bool>("Latest")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("StartSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("TelNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("EmploymentHistories");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EmptyCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("emptypcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emptypname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("empty_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EpfCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("epfcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descrip");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("epf_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldArea", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("fldareaid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fldareaname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("field_area_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldAreaCode")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("FieldExperiences");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.GL1Code", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("glseg1code");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("glseg1name");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("gl1_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.GL2Code", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("glseg2code");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("glseg2name");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("gl2_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Hobby", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("hbycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hbyname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("hobby_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.HrAdapterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "CompanyId")
                        .IsUnique();

                    b.ToTable("HrAdapterData");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Industry", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("indstrycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indstryname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("industry_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Job", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("jobcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobpost");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("job_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobGradeCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("gradecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gradename");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("job_grade_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("langcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("langname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("language_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.MaritalStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("marstacode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marstaname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("marital_status_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Nationality", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("nationcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationame");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("nationality_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PCBCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("pcbtabcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pcbtabdesc");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("pcb_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PayGroupCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("paygrpcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descrip");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("pay_group_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PensionCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("pesncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("pension_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("jobcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobpost");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("position_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CGPA")
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHighest")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinSchoolDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherGradeInfo")
                        .HasColumnType("text");

                    b.Property<string>("QualificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeCode")
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeName")
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeRank")
                        .HasColumnType("text");

                    b.Property<string>("QualificationName")
                        .HasColumnType("text");

                    b.Property<string>("QualificationSubCode")
                        .HasColumnType("text");

                    b.Property<string>("QualificationSubName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolTelNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("SinceWhenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("qlfcatid");

                    b.Property<string>("SubCode")
                        .HasColumnType("text")
                        .HasColumnName("qlfsubid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfcatname");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfsubname");

                    b.HasKey("Code", "SubCode", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("qualification_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationGrade", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("qlfgradecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfgradename");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("qualification_grades");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Race", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("racecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("racename");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("race_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Religion", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("religncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relignname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("religion_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Salutation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("salucode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saludesc");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("salutation_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SectionCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("sectiocode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sectioname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("section_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SecurityCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("grpid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grpname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("security_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfficeSkills")
                        .HasColumnType("text");

                    b.Property<string>("OtherRelevantSkills")
                        .HasColumnType("text");

                    b.Property<string>("OtherSkillInformation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SocsoCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("soctabcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soctabdesc");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("socso_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.StatutoryCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("corefcode");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compnycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("statutory_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ThanksPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NextStepsMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThanksFooter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThanksMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThanksTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ThanksPages");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.UnitCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("unitcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unitname");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("unit_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email", "CompanyId")
                        .IsUnique();

                    b.HasIndex("IcNumber", "CompanyId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.VECode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("vecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Code");

                    b.HasIndex("CompanyId");

                    b.ToTable("ve_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Application", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentBackend.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.BranchCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Candidate", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.CountryOrigin", "CountryOfOrigin")
                        .WithMany()
                        .HasForeignKey("CountryOfOriginCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CountryOfOrigin");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("Race");

                    b.Navigation("Religion");

                    b.Navigation("Salutation");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateHobby", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("Hobbies")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateLanguage", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("Languages")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateResume", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CessationReason", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CompanyCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ContactInformation", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithOne("ContactInfo")
                        .HasForeignKey("RecruitmentBackend.Models.ContactInformation", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CountryOrigin", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.DepartmentCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.DivisionCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EmploymentHistory", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EmptyCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EpfCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldArea", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldExperience", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("FieldExperiences")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.GL1Code", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.GL2Code", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Hobby", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Industry", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Job", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobGradeCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Language", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.MaritalStatus", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Nationality", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PCBCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PayGroupCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.PensionCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Qualification", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithMany("Qualifications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationGrade", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Race", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Religion", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Salutation", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SectionCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SecurityCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Skill", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Candidate", "Candidate")
                        .WithOne("Skills")
                        .HasForeignKey("RecruitmentBackend.Models.Skill", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.SocsoCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.StatutoryCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ThanksPage", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.UnitCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.VECode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Candidate", b =>
                {
                    b.Navigation("ContactInfo");

                    b.Navigation("EmploymentHistory");

                    b.Navigation("FieldExperiences");

                    b.Navigation("Hobbies");

                    b.Navigation("Languages");

                    b.Navigation("Qualifications");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
